spring:
  data:
    cassandra:
      keyspace-name: main
      username: MNYyJIRlQYgqzWOZsRatwkzq
      password: NWs0yDzP2MY8TXpdfp,.qm3N93azmqj6rM6Oo+MGOw5eMFX2N0qs-cmR,iX.fi,.QJOEUgJBoi8JShd-jCbcKcB1oTX_i7c89Xo4EOHlNT3wCjZBSCaBjXlyyBnHu+c.
      schema-action: create-if-not-exists
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s

datadump-location:
  author: src/main/resources/test-author.txt
  work: src/main/resources/test-work.txt

datastax.astra:
  secure-connect-bundle: secure-connect-betterreads.zip


astra.db:
  id: 8f90298f-4ab9-4500-9d0d-c8d87e9bd251
  region: asia-south1
  keyspace: main
  application.token: AstraCS:MNYyJIRlQYgqzWOZsRatwkzq:9ad905da36753f5cdde5cc803a57d4292680e3d53761f8d75cde7c62e193d26d
